inputFile:
    base:
        location: work-input
server:
    shutdown: graceful
    port: 9011
spring:
    application:
        name: batch-demo
    batch:
        jdbc:
            initialize-schema: always
        job:
            enabled: false
    datasource:
        url: jdbc:h2:mem:myDB;INIT=RUNSCRIPT FROM 'classpath:org/springframework/batch/core/schema-h2.sql';
    h2:
        console:
            enabled: true
    jpa:
        show-sql: false
    main:
        allow-circular-references: true
    threads:
        virtual:
            enabled: true
